spring.application.name=googleAuth

spring.security.oauth2.client.registration.google.client-id=262125842551-cknviknbac0hu69789sm7i8kg60pmr1p.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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